FROM alpine:3.14

ENV TRACCAR_VERSION 4.14

WORKDIR /opt/traccar

COPY traccar*.zip /tmp/

RUN set -ex && \
    apk add --no-cache --no-progress openjdk11-jre-headless wget && \
    unzip -qo /tmp/traccar-linux-64*.zip -d /opt/traccar && \
    rm /tmp/traccar.zip && \
    apk del wget

ENTRYPOINT ["java", "-Xms512m", "-Xmx512m", "-Djava.net.preferIPv4Stack=true"]

CMD ["-jar", "tracker-server.jar", "conf/traccar.xml"]
