FROM public.ecr.aws/socar/adoptopenjdk/openjdk11:alpine-jre-11.0.10_9

ENV TRACCAR_VERSION 4.14

WORKDIR /opt/traccar

COPY traccar*.zip /tmp/

RUN set -ex && \
    unzip -qo /tmp/traccar*.zip -d /opt/traccar && \
    rm -rf /var/lib/apt/lists/* /tmp/*

ENTRYPOINT ["java", "-Xms512m", "-Xmx512m", "-Djava.net.preferIPv4Stack=true"]

CMD ["-jar", "tracker-server.jar", "conf/traccar.xml"]
